/*
 This is an interface for simpleMPC_solver that can be used to call the solver generated by FORCES Pro
*/ 

#include "../include/simpleMPC_solver.h"
#include "../include/internal_simpleMPC_solver_1.h"
#include <stdio.h>

/* For Visual Studio 2015 Compatibility */
#if (_MSC_VER >= 1900)
FILE _iob[3];
FILE * __cdecl __iob_func(void)
{
    _iob[0] = *stdin;
    _iob[1] = *stdout;
    _iob[2] = *stderr;
    return _iob;
}
#endif

extern solver_int32_default simpleMPC_solver_solve(simpleMPC_solver_params *params, simpleMPC_solver_output *output, simpleMPC_solver_info *info, FILE *fs) 
{
	/* Some memory */
	internal_simpleMPC_solver_1_params params_1;
	internal_simpleMPC_solver_1_output output_1;
	internal_simpleMPC_solver_1_info info_1;

	solver_int32_default exitflag;
	/* define variables */
	solver_int32_default i;
	/* SOLVER 1 --------------------------------------------------------*/
	/*Assigning parameter values of solver #1*/
	/*Assigning parameter values of solver #1*/
	params_1.p_1[0] = (7.947647385311364054 * params->param1[2]);
	params_1.p_1[0] += (7.947647385311364054 * params->param1[2]);
	params_1.p_1[0] += (21.238899412075333828 * params->param1[1]);
	params_1.p_1[0] += (21.238899412075333828 * params->param1[1]);
	params_1.p_1[0] += (46.071001497955165860 * params->param1[0]);
	params_1.p_1[0] += (46.071001497955165860 * params->param1[0]);
	params_1.p_1[1] = (11.051026177946820184 * params->param1[2]);
	params_1.p_1[1] += (11.051026177946820184 * params->param1[2]);
	params_1.p_1[1] += (38.248363806338353754 * params->param1[1]);
	params_1.p_1[1] += (38.248363806338353754 * params->param1[1]);
	params_1.p_1[1] += (10.692320666517783678 * params->param1[0]);
	params_1.p_1[1] += (10.692320666517783678 * params->param1[0]);
	params_1.p_1[2] = (7.896633457962514591 * params->param1[2]);
	params_1.p_1[2] += (7.896633457962514591 * params->param1[2]);
	params_1.p_1[2] += (20.883416886229877463 * params->param1[1]);
	params_1.p_1[2] += (20.883416886229877463 * params->param1[1]);
	params_1.p_1[2] += (44.647806584705740818 * params->param1[0]);
	params_1.p_1[2] += (44.647806584705740818 * params->param1[0]);
	params_1.p_1[3] = (11.376695945930901388 * params->param1[2]);
	params_1.p_1[3] += (11.376695945930901388 * params->param1[2]);
	params_1.p_1[3] += (36.460043942420945484 * params->param1[1]);
	params_1.p_1[3] += (36.460043942420945484 * params->param1[1]);
	params_1.p_1[3] += (10.649667051895452374 * params->param1[0]);
	params_1.p_1[3] += (10.649667051895452374 * params->param1[0]);
	params_1.p_1[4] = (7.835487760152771486 * params->param1[2]);
	params_1.p_1[4] += (7.835487760152771486 * params->param1[2]);
	params_1.p_1[4] += (20.510020264497725861 * params->param1[1]);
	params_1.p_1[4] += (20.510020264497725861 * params->param1[1]);
	params_1.p_1[4] += (43.247872099639266708 * params->param1[0]);
	params_1.p_1[4] += (43.247872099639266708 * params->param1[0]);
	params_1.p_1[5] = (11.630185176303122319 * params->param1[2]);
	params_1.p_1[5] += (11.630185176303122319 * params->param1[2]);
	params_1.p_1[5] += (34.771244702485795131 * params->param1[1]);
	params_1.p_1[5] += (34.771244702485795131 * params->param1[1]);
	params_1.p_1[5] += (10.586211528111359570 * params->param1[0]);
	params_1.p_1[5] += (10.586211528111359570 * params->param1[0]);
	params_1.p_1[6] = (7.764293316795747302 * params->param1[2]);
	params_1.p_1[6] += (7.764293316795747302 * params->param1[2]);
	params_1.p_1[6] += (20.119908445961343091 * params->param1[1]);
	params_1.p_1[6] += (20.119908445961343091 * params->param1[1]);
	params_1.p_1[6] += (41.870259164699419330 * params->param1[0]);
	params_1.p_1[6] += (41.870259164699419330 * params->param1[0]);
	params_1.p_1[7] = (11.818381034544099606 * params->param1[2]);
	params_1.p_1[7] += (11.818381034544099606 * params->param1[2]);
	params_1.p_1[7] += (33.174349187796060789 * params->param1[1]);
	params_1.p_1[7] += (33.174349187796060789 * params->param1[1]);
	params_1.p_1[7] += (10.503500740024351856 * params->param1[0]);
	params_1.p_1[7] += (10.503500740024351856 * params->param1[0]);
	params_1.p_1[8] = (7.683164296532013715 * params->param1[2]);
	params_1.p_1[8] += (7.683164296532013715 * params->param1[2]);
	params_1.p_1[8] += (19.714198896168799280 * params->param1[1]);
	params_1.p_1[8] += (19.714198896168799280 * params->param1[1]);
	params_1.p_1[8] += (40.514062158867737651 * params->param1[0]);
	params_1.p_1[8] += (40.514062158867737651 * params->param1[0]);
	params_1.p_1[9] = (11.947550198134814892 * params->param1[2]);
	params_1.p_1[9] += (11.947550198134814892 * params->param1[2]);
	params_1.p_1[9] += (31.662334500388730874 * params->param1[1]);
	params_1.p_1[9] += (31.662334500388730874 * params->param1[1]);
	params_1.p_1[9] += (10.402959359772870229 * params->param1[0]);
	params_1.p_1[9] += (10.402959359772870229 * params->param1[0]);
	params_1.p_1[10] = (7.592242130205973716 * params->param1[2]);
	params_1.p_1[10] += (7.592242130205973716 * params->param1[2]);
	params_1.p_1[10] += (19.293933740835502277 * params->param1[1]);
	params_1.p_1[10] += (19.293933740835502277 * params->param1[1]);
	params_1.p_1[10] += (39.178406969782209046 * params->param1[0]);
	params_1.p_1[10] += (39.178406969782209046 * params->param1[0]);
	params_1.p_1[11] = (12.023391020359635917 * params->param1[2]);
	params_1.p_1[11] += (12.023391020359635917 * params->param1[2]);
	params_1.p_1[11] += (30.228722137256404778 * params->param1[1]);
	params_1.p_1[11] += (30.228722137256404778 * params->param1[1]);
	params_1.p_1[11] += (10.285899292598660537 * params->param1[0]);
	params_1.p_1[11] += (10.285899292598660537 * params->param1[0]);
	params_1.p_1[12] = (7.491692044374826054 * params->param1[2]);
	params_1.p_1[12] += (7.491692044374826054 * params->param1[2]);
	params_1.p_1[12] += (18.860085426579278334 * params->param1[1]);
	params_1.p_1[12] += (18.860085426579278334 * params->param1[1]);
	params_1.p_1[12] += (37.862449357928149141 * params->param1[0]);
	params_1.p_1[12] += (37.862449357928149141 * params->param1[0]);
	params_1.p_1[13] = (12.051081225641343764 * params->param1[2]);
	params_1.p_1[13] += (12.051081225641343764 * params->param1[2]);
	params_1.p_1[13] += (28.867532393206996488 * params->param1[1]);
	params_1.p_1[13] += (28.867532393206996488 * params->param1[1]);
	params_1.p_1[13] += (10.153528103716608300 * params->param1[0]);
	params_1.p_1[13] += (10.153528103716608300 * params->param1[0]);
	params_1.p_1[14] = (7.381699975191624574 * params->param1[2]);
	params_1.p_1[14] += (7.381699975191624574 * params->param1[2]);
	params_1.p_1[14] += (18.413561986079905353 * params->param1[1]);
	params_1.p_1[14] += (18.413561986079905353 * params->param1[1]);
	params_1.p_1[14] += (36.565373426505324517 * params->param1[0]);
	params_1.p_1[14] += (36.565373426505324517 * params->param1[0]);
	params_1.p_1[15] = (12.035321504143482230 * params->param1[2]);
	params_1.p_1[15] += (12.035321504143482230 * params->param1[2]);
	params_1.p_1[15] += (27.573242431359048510 * params->param1[1]);
	params_1.p_1[15] += (27.573242431359048510 * params->param1[1]);
	params_1.p_1[15] += (10.006956726615362285 * params->param1[0]);
	params_1.p_1[15] += (10.006956726615362285 * params->param1[0]);
	params_1.p_1[16] = (7.262469831208513860 * params->param1[2]);
	params_1.p_1[16] += (7.262469831208513860 * params->param1[2]);
	params_1.p_1[16] += (17.955211942278946680 * params->param1[1]);
	params_1.p_1[16] += (17.955211942278946680 * params->param1[1]);
	params_1.p_1[16] += (35.286390190704956638 * params->param1[0]);
	params_1.p_1[16] += (35.286390190704956638 * params->param1[0]);
	params_1.p_1[17] = (11.980375342068771971 * params->param1[2]);
	params_1.p_1[17] += (11.980375342068771971 * params->param1[2]);
	params_1.p_1[17] += (26.340747707853470416 * params->param1[1]);
	params_1.p_1[17] += (26.340747707853470416 * params->param1[1]);
	params_1.p_1[17] += (9.847206507850222224 * params->param1[0]);
	params_1.p_1[17] += (9.847206507850222224 * params->param1[0]);
	params_1.p_1[18] = (7.134221076599310152 * params->param1[2]);
	params_1.p_1[18] += (7.134221076599310152 * params->param1[2]);
	params_1.p_1[18] += (17.485828883714269466 * params->param1[1]);
	params_1.p_1[18] += (17.485828883714269466 * params->param1[1]);
	params_1.p_1[18] += (34.024736240721360048 * params->param1[0]);
	params_1.p_1[18] += (34.024736240721360048 * params->param1[0]);
	params_1.p_1[19] = (11.890105395334789051 * params->param1[2]);
	params_1.p_1[19] += (11.890105395334789051 * params->param1[2]);
	params_1.p_1[19] += (25.165326462617343850 * params->param1[1]);
	params_1.p_1[19] += (25.165326462617343850 * params->param1[1]);
	params_1.p_1[19] += (9.675215638478473323 * params->param1[0]);
	params_1.p_1[19] += (9.675215638478473323 * params->param1[0]);
	params_1.p_1[20] = (6.997186609025209947 * params->param1[2]);
	params_1.p_1[20] += (6.997186609025209947 * params->param1[2]);
	params_1.p_1[20] += (17.006155740796920384 * params->param1[1]);
	params_1.p_1[20] += (17.006155740796920384 * params->param1[1]);
	params_1.p_1[20] += (32.779672493378569698 * params->param1[0]);
	params_1.p_1[20] += (32.779672493378569698 * params->param1[0]);
	params_1.p_1[21] = (11.768006687900038898 * params->param1[2]);
	params_1.p_1[21] += (11.768006687900038898 * params->param1[2]);
	params_1.p_1[21] += (24.042607011093494407 * params->param1[1]);
	params_1.p_1[21] += (24.042607011093494407 * params->param1[1]);
	params_1.p_1[21] += (9.491845017750584645 * params->param1[0]);
	params_1.p_1[21] += (9.491845017750584645 * params->param1[0]);
	params_1.p_1[22] = (6.851610908884973483 * params->param1[2]);
	params_1.p_1[22] += (6.851610908884973483 * params->param1[2]);
	params_1.p_1[22] += (16.516888790769229445 * params->param1[1]);
	params_1.p_1[22] += (16.516888790769229445 * params->param1[1]);
	params_1.p_1[22] += (31.550483027775811706 * params->param1[0]);
	params_1.p_1[22] += (31.550483027775811706 * params->param1[0]);
	params_1.p_1[23] = (11.617236891745772454 * params->param1[2]);
	params_1.p_1[23] += (11.617236891745772454 * params->param1[2]);
	params_1.p_1[23] += (22.968537592924246127 * params->param1[1]);
	params_1.p_1[23] += (22.968537592924246127 * params->param1[1]);
	params_1.p_1[23] += (9.297883590474560478 * params->param1[0]);
	params_1.p_1[23] += (9.297883590474560478 * params->param1[0]);
	params_1.p_1[24] = (6.697748439020619671 * params->param1[2]);
	params_1.p_1[24] += (6.697748439020619671 * params->param1[2]);
	params_1.p_1[24] += (16.018681417216591001 * params->param1[1]);
	params_1.p_1[24] += (16.018681417216591001 * params->param1[1]);
	params_1.p_1[24] += (30.336474000852284405 * params->param1[0]);
	params_1.p_1[24] += (30.336474000852284405 * params->param1[0]);
	params_1.p_1[25] = (11.440643923206494037 * params->param1[2]);
	params_1.p_1[25] += (11.440643923206494037 * params->param1[2]);
	params_1.p_1[25] += (21.939358552810567460 * params->param1[1]);
	params_1.p_1[25] += (21.939358552810567460 * params->param1[1]);
	params_1.p_1[25] += (9.094053195583422067 * params->param1[0]);
	params_1.p_1[25] += (9.094053195583422067 * params->param1[0]);
	params_1.p_1[26] = (6.535862276109967617 * params->param1[2]);
	params_1.p_1[26] += (6.535862276109967617 * params->param1[2]);
	params_1.p_1[26] += (15.512147648327491822 * params->param1[1]);
	params_1.p_1[26] += (15.512147648327491822 * params->param1[1]);
	params_1.p_1[26] += (29.136972639243087002 * params->param1[0]);
	params_1.p_1[26] += (29.136972639243087002 * params->param1[0]);
	params_1.p_1[27] = (11.240791069815879055 * params->param1[2]);
	params_1.p_1[27] += (11.240791069815879055 * params->param1[2]);
	params_1.p_1[27] += (20.951576646301788287 * params->param1[1]);
	params_1.p_1[27] += (20.951576646301788287 * params->param1[1]);
	params_1.p_1[27] += (8.881012959828042952 * params->param1[0]);
	params_1.p_1[27] += (8.881012959828042952 * params->param1[0]);
	params_1.p_1[28] = (6.366222956984636028 * params->param1[2]);
	params_1.p_1[28] += (6.366222956984636028 * params->param1[2]);
	params_1.p_1[28] += (14.997865496594997126 * params->param1[1]);
	params_1.p_1[28] += (14.997865496594997126 * params->param1[1]);
	params_1.p_1[28] += (27.951326304249565879 * params->param1[0]);
	params_1.p_1[28] += (27.951326304249565879 * params->param1[0]);
	params_1.p_1[29] = (11.019979842939047643 * params->param1[2]);
	params_1.p_1[29] += (11.019979842939047643 * params->param1[2]);
	params_1.p_1[29] += (20.001941279241304272 * params->param1[1]);
	params_1.p_1[29] += (20.001941279241304272 * params->param1[1]);
	params_1.p_1[29] += (8.659363267162184741 * params->param1[0]);
	params_1.p_1[29] += (8.659363267162184741 * params->param1[0]);
	params_1.p_1[30] = (6.189107524982275343 * params->param1[2]);
	params_1.p_1[30] += (6.189107524982275343 * params->param1[2]);
	params_1.p_1[30] += (14.476380121316090310 * params->param1[1]);
	params_1.p_1[30] += (14.476380121316090310 * params->param1[1]);
	params_1.p_1[30] += (26.778901627180488276 * params->param1[0]);
	params_1.p_1[30] += (26.778901627180488276 * params->param1[0]);
	params_1.p_1[31] = (10.780270734053392090 * params->param1[2]);
	params_1.p_1[31] += (10.780270734053392090 * params->param1[2]);
	params_1.p_1[31] += (19.087422504118702449 * params->param1[1]);
	params_1.p_1[31] += (19.087422504118702449 * params->param1[1]);
	params_1.p_1[31] += (8.429649331258417533 * params->param1[0]);
	params_1.p_1[31] += (8.429649331258417533 * params->param1[0]);
	params_1.p_1[32] = (6.004798763189249655 * params->param1[2]);
	params_1.p_1[32] += (6.004798763189249655 * params->param1[2]);
	params_1.p_1[32] += (13.948206834064221127 * params->param1[1]);
	params_1.p_1[32] += (13.948206834064221127 * params->param1[1]);
	params_1.p_1[32] += (25.619083712739460168 * params->param1[0]);
	params_1.p_1[32] += (25.619083712739460168 * params->param1[0]);
	params_1.p_1[33] = (10.523502036485933075 * params->param1[2]);
	params_1.p_1[33] += (10.523502036485933075 * params->param1[2]);
	params_1.p_1[33] += (18.205190609770355081 * params->param1[1]);
	params_1.p_1[33] += (18.205190609770355081 * params->param1[1]);
	params_1.p_1[33] += (8.192364395668857213 * params->param1[0]);
	params_1.p_1[33] += (8.192364395668857213 * params->param1[0]);
	params_1.p_1[34] = (5.813584603068353118 * params->param1[2]);
	params_1.p_1[34] += (5.813584603068353118 * params->param1[2]);
	params_1.p_1[34] += (13.413833966275628740 * params->param1[1]);
	params_1.p_1[34] += (13.413833966275628740 * params->param1[1]);
	params_1.p_1[34] += (24.471275408541156793 * params->param1[0]);
	params_1.p_1[34] += (24.471275408541156793 * params->param1[0]);
	params_1.p_1[35] = (10.251306879594149990 * params->param1[2]);
	params_1.p_1[35] += (10.251306879594149990 * params->param1[2]);
	params_1.p_1[35] += (17.352597152827090810 * params->param1[1]);
	params_1.p_1[35] += (17.352597152827090810 * params->param1[1]);
	params_1.p_1[35] += (7.947952583401508342 * params->param1[0]);
	params_1.p_1[35] += (7.947952583401508342 * params->param1[0]);
	params_1.p_1[36] = (5.615757698508200058 * params->param1[2]);
	params_1.p_1[36] += (5.615757698508200058 * params->param1[2]);
	params_1.p_1[36] += (12.873725617194050841 * params->param1[1]);
	params_1.p_1[36] += (12.873725617194050841 * params->param1[1]);
	params_1.p_1[36] += (23.334896639237822313 * params->param1[0]);
	params_1.p_1[36] += (23.334896639237822313 * params->param1[0]);
	params_1.p_1[37] = (9.965128608676231181 * params->param1[2]);
	params_1.p_1[37] += (9.965128608676231181 * params->param1[2]);
	params_1.p_1[37] += (16.527157290120186417 * params->param1[1]);
	params_1.p_1[37] += (16.527157290120186417 * params->param1[1]);
	params_1.p_1[37] += (7.696811415100701659 * params->param1[0]);
	params_1.p_1[37] += (7.696811415100701659 * params->param1[0]);
	params_1.p_1[38] = (5.411615156788688985 * params->param1[2]);
	params_1.p_1[38] += (5.411615156788688985 * params->param1[2]);
	params_1.p_1[38] += (12.328324299655161411 * params->param1[1]);
	params_1.p_1[38] += (12.328324299655161411 * params->param1[1]);
	params_1.p_1[38] += (22.209383804130286677 * params->param1[0]);
	params_1.p_1[38] += (22.209383804130286677 * params->param1[0]);
	params_1.p_1[39] = (9.666234631212180517 * params->param1[2]);
	params_1.p_1[39] += (9.666234631212180517 * params->param1[2]);
	params_1.p_1[39] += (15.726533281007178289 * params->param1[1]);
	params_1.p_1[39] += (15.726533281007178289 * params->param1[1]);
	params_1.p_1[39] += (7.439294012579193982 * params->param1[0]);
	params_1.p_1[39] += (7.439294012579193982 * params->param1[0]);
	params_1.p_1[40] = (5.201458419341729922 * params->param1[2]);
	params_1.p_1[40] += (5.201458419341729922 * params->param1[2]);
	params_1.p_1[40] += (11.778053500555367705 * params->param1[1]);
	params_1.p_1[40] += (11.778053500555367705 * params->param1[1]);
	params_1.p_1[40] += (21.094189237527828595 * params->param1[0]);
	params_1.p_1[40] += (21.094189237527828595 * params->param1[0]);
	params_1.p_1[41] = (9.355728838272506565 * params->param1[2]);
	params_1.p_1[41] += (9.355728838272506565 * params->param1[2]);
	params_1.p_1[41] += (14.948519037340711080 * params->param1[1]);
	params_1.p_1[41] += (14.948519037340711080 * params->param1[1]);
	params_1.p_1[41] += (7.175711002131651917 * params->param1[0]);
	params_1.p_1[41] += (7.175711002131651917 * params->param1[0]);
	params_1.p_1[42] = (4.985593286509136135 * params->param1[2]);
	params_1.p_1[42] += (4.985593286509136135 * params->param1[2]);
	params_1.p_1[42] += (11.223320172335235156 * params->param1[1]);
	params_1.p_1[42] += (11.223320172335235156 * params->param1[1]);
	params_1.p_1[42] += (19.988780731511141653 * params->param1[0]);
	params_1.p_1[42] += (19.988780731511141653 * params->param1[0]);
	params_1.p_1[43] = (9.034562698997127939 * params->param1[2]);
	params_1.p_1[43] += (9.034562698997127939 * params->param1[2]);
	params_1.p_1[43] += (14.191025606642712731 * params->param1[1]);
	params_1.p_1[43] += (14.191025606642712731 * params->param1[1]);
	params_1.p_1[43] += (6.906332129846880719 * params->param1[0]);
	params_1.p_1[43] += (6.906332129846880719 * params->param1[0]);
	params_1.p_1[44] = (4.764330081770407510 * params->param1[2]);
	params_1.p_1[44] += (4.764330081770407510 * params->param1[2]);
	params_1.p_1[44] += (10.664517171411919350 * params->param1[1]);
	params_1.p_1[44] += (10.664517171411919350 * params->param1[1]);
	params_1.p_1[44] += (18.892641121145281602 * params->param1[0]);
	params_1.p_1[44] += (18.892641121145281602 * params->param1[0]);
	params_1.p_1[45] = (8.703545115860613635 * params->param1[2]);
	params_1.p_1[45] += (8.703545115860613635 * params->param1[2]);
	params_1.p_1[45] += (13.452067481022309536 * params->param1[1]);
	params_1.p_1[45] += (13.452067481022309536 * params->param1[1]);
	params_1.p_1[45] += (6.631387599012832368 * params->param1[0]);
	params_1.p_1[45] += (6.631387599012832368 * params->param1[0]);
	params_1.p_1[46] = (4.537983952142097266 * params->param1[2]);
	params_1.p_1[46] += (4.537983952142097266 * params->param1[2]);
	params_1.p_1[46] += (10.102025659214811881 * params->param1[1]);
	params_1.p_1[46] += (10.102025659214811881 * params->param1[1]);
	params_1.p_1[46] += (17.805267932587618418 * params->param1[0]);
	params_1.p_1[46] += (17.805267932587618418 * params->param1[0]);
	params_1.p_1[47] = (8.363351118923414873 * params->param1[2]);
	params_1.p_1[47] += (8.363351118923414873 * params->param1[2]);
	params_1.p_1[47] += (12.729749630541377314 * params->param1[1]);
	params_1.p_1[47] += (12.729749630541377314 * params->param1[1]);
	params_1.p_1[47] += (6.351069137657875174 * params->param1[0]);
	params_1.p_1[47] += (6.351069137657875174 * params->param1[0]);
	params_1.p_1[48] = (4.306875302647044990 * params->param1[2]);
	params_1.p_1[48] += (4.306875302647044990 * params->param1[2]);
	params_1.p_1[48] += (9.536217481312329269 * params->param1[1]);
	params_1.p_1[48] += (9.536217481312329269 * params->param1[1]);
	params_1.p_1[48] += (16.726173094942637931 * params->param1[0]);
	params_1.p_1[48] += (16.726173094942637931 * params->param1[0]);
	params_1.p_1[49] = (8.014529468350092500 * params->param1[2]);
	params_1.p_1[49] += (8.014529468350092500 * params->param1[2]);
	params_1.p_1[49] += (12.022255165133376664 * params->param1[1]);
	params_1.p_1[49] += (12.022255165133376664 * params->param1[1]);
	params_1.p_1[49] += (6.065530802278808586 * params->param1[0]);
	params_1.p_1[49] += (6.065530802278808586 * params->param1[0]);
	params_1.p_1[50] = (4.071330363925373064 * params->param1[2]);
	params_1.p_1[50] += (4.071330363925373064 * params->param1[2]);
	params_1.p_1[50] += (8.967457540063993093 * params->param1[1]);
	params_1.p_1[50] += (8.967457540063993093 * params->param1[1]);
	params_1.p_1[50] += (15.654882717133379089 * params->param1[0]);
	params_1.p_1[50] += (15.654882717133379089 * params->param1[0]);
	params_1.p_1[51] = (7.657509226087165999 * params->param1[2]);
	params_1.p_1[51] += (7.657509226087165999 * params->param1[2]);
	params_1.p_1[51] += (11.327833533859568149 * params->param1[1]);
	params_1.p_1[51] += (11.327833533859568149 * params->param1[1]);
	params_1.p_1[51] += (5.774889521855502750 * params->param1[0]);
	params_1.p_1[51] += (5.774889521855502750 * params->param1[0]);
	params_1.p_1[52] = (3.831681893218872315 * params->param1[2]);
	params_1.p_1[52] += (3.831681893218872315 * params->param1[2]);
	params_1.p_1[52] += (8.396106176290963674 * params->param1[1]);
	params_1.p_1[52] += (8.396106176290963674 * params->param1[1]);
	params_1.p_1[52] += (14.590936931492063167 * params->param1[0]);
	params_1.p_1[52] += (14.590936931492063167 * params->param1[0]);
	params_1.p_1[53] = (7.292605349670841619 * params->param1[2]);
	params_1.p_1[53] += (7.292605349670841619 * params->param1[2]);
	params_1.p_1[53] += (10.644789174277567767 * params->param1[1]);
	params_1.p_1[53] += (10.644789174277567767 * params->param1[1]);
	params_1.p_1[53] += (5.479225384329216908 * params->param1[0]);
	params_1.p_1[53] += (5.479225384329216908 * params->param1[0]);
	params_1.p_1[54] = (3.588270010115280684 * params->param1[2]);
	params_1.p_1[54] += (3.588270010115280684 * params->param1[2]);
	params_1.p_1[54] += (7.822521575630013047 * params->param1[1]);
	params_1.p_1[54] += (7.822521575630013047 * params->param1[1]);
	params_1.p_1[54] += (13.533889806222786589 * params->param1[0]);
	params_1.p_1[54] += (13.533889806222786589 * params->param1[0]);
	params_1.p_1[55] = (6.920023353618983464 * params->param1[2]);
	params_1.p_1[55] += (6.920023353618983464 * params->param1[2]);
	params_1.p_1[55] += (9.971470528030245362 * params->param1[1]);
	params_1.p_1[55] += (9.971470528030245362 * params->param1[1]);
	params_1.p_1[55] += (5.178581665812016510 * params->param1[0]);
	params_1.p_1[55] += (5.178581665812016510 * params->param1[0]);
	params_1.p_1[56] = (3.341443169597974272 * params->param1[2]);
	params_1.p_1[56] += (3.341443169597974272 * params->param1[2]);
	params_1.p_1[56] += (7.247062215522437789 * params->param1[1]);
	params_1.p_1[56] += (7.247062215522437789 * params->param1[1]);
	params_1.p_1[56] += (12.483309329360459117 * params->param1[0]);
	params_1.p_1[56] += (12.483309329360459117 * params->param1[0]);
	params_1.p_1[57] = (6.539863076694592436 * params->param1[2]);
	params_1.p_1[57] += (6.539863076694592436 * params->param1[2]);
	params_1.p_1[57] += (9.306259341463576362 * params->param1[1]);
	params_1.p_1[57] += (9.306259341463576362 * params->param1[1]);
	params_1.p_1[57] += (4.872964600883986641 * params->param1[0]);
	params_1.p_1[57] += (4.872964600883986641 * params->param1[0]);

	params_1.p_2[0] = Inf;
	params_1.p_2[0] += (0.000321959672365564 * params->param1[2]);
	params_1.p_2[0] += (0.021603187129383035 * params->param1[1]);
	params_1.p_2[0] += (0.974944509814621108 * params->param1[0]);
	params_1.p_2[1] = 0.250000000000000000;
	params_1.p_2[1] += (0.028310578008216847 * params->param1[2]);
	params_1.p_2[1] += (0.945763577721654203 * params->param1[1]);
	params_1.p_2[1] += (0.010801593564691517 * params->param1[0]);
	params_1.p_2[2] = Inf;
	params_1.p_2[2] += (0.942104020593489966 * params->param1[2]);
	params_1.p_2[2] += (0.022648462406573474 * params->param1[1]);
	params_1.p_2[2] += (0.000128783868946226 * params->param1[0]);
	params_1.p_2[3] = 10.000000000000000000;
	params_1.p_2[3] += (-0.000321959672365564 * params->param1[2]);
	params_1.p_2[3] += (-0.021603187129383035 * params->param1[1]);
	params_1.p_2[3] += (-0.974944509814621108 * params->param1[0]);
	params_1.p_2[4] = 4.750000000000000000;
	params_1.p_2[4] += (-0.028310578008216847 * params->param1[2]);
	params_1.p_2[4] += (-0.945763577721654203 * params->param1[1]);
	params_1.p_2[4] += (-0.010801593564691517 * params->param1[0]);
	params_1.p_2[5] = Inf;
	params_1.p_2[5] += (-0.942104020593489966 * params->param1[2]);
	params_1.p_2[5] += (-0.022648462406573474 * params->param1[1]);
	params_1.p_2[5] += (-0.000128783868946226 * params->param1[0]);
	params_1.p_2[6] = Inf;
	params_1.p_2[6] += (0.001228811031211586 * params->param1[2]);
	params_1.p_2[6] += (0.041500708127501576 * params->param1[1]);
	params_1.p_2[6] += (0.950750187527957591 * params->param1[0]);
	params_1.p_2[7] = 0.250000000000000000;
	params_1.p_2[7] += (0.053450100588810986 * params->param1[2]);
	params_1.p_2[7] += (0.895343284853664545 * params->param1[1]);
	params_1.p_2[7] += (0.020750354063750788 * params->param1[0]);
	params_1.p_2[8] = Inf;
	params_1.p_2[8] += (0.888201218143358728 * params->param1[2]);
	params_1.p_2[8] += (0.042760080471048782 * params->param1[1]);
	params_1.p_2[8] += (0.000491524412484634 * params->param1[0]);
	params_1.p_2[9] = 10.000000000000000000;
	params_1.p_2[9] += (-0.001228811031211586 * params->param1[2]);
	params_1.p_2[9] += (-0.041500708127501576 * params->param1[1]);
	params_1.p_2[9] += (-0.950750187527957591 * params->param1[0]);
	params_1.p_2[10] = 4.750000000000000000;
	params_1.p_2[10] += (-0.053450100588810986 * params->param1[2]);
	params_1.p_2[10] += (-0.895343284853664545 * params->param1[1]);
	params_1.p_2[10] += (-0.020750354063750788 * params->param1[0]);
	params_1.p_2[11] = Inf;
	params_1.p_2[11] += (-0.888201218143358728 * params->param1[2]);
	params_1.p_2[11] += (-0.042760080471048782 * params->param1[1]);
	params_1.p_2[11] += (-0.000491524412484634 * params->param1[0]);
	params_1.p_2[12] = Inf;
	params_1.p_2[12] += (0.002638680066771940 * params->param1[2]);
	params_1.p_2[12] += (0.059816923091555688 * params->param1[1]);
	params_1.p_2[12] += (0.927377107568482795 * params->param1[0]);
	params_1.p_2[13] = 0.250000000000000000;
	params_1.p_2[13] += (0.075709921353023915 * params->param1[2]);
	params_1.p_2[13] += (0.848441904747913367 * params->param1[1]);
	params_1.p_2[13] += (0.029908461545777840 * params->param1[0]);
	params_1.p_2[14] = Inf;
	params_1.p_2[14] += (0.837988659553745796 * params->param1[2]);
	params_1.p_2[14] += (0.060567937082419122 * params->param1[1]);
	params_1.p_2[14] += (0.001055472026708776 * params->param1[0]);
	params_1.p_2[15] = 10.000000000000000000;
	params_1.p_2[15] += (-0.002638680066771940 * params->param1[2]);
	params_1.p_2[15] += (-0.059816923091555688 * params->param1[1]);
	params_1.p_2[15] += (-0.927377107568482795 * params->param1[0]);
	params_1.p_2[16] = 4.750000000000000000;
	params_1.p_2[16] += (-0.075709921353023915 * params->param1[2]);
	params_1.p_2[16] += (-0.848441904747913367 * params->param1[1]);
	params_1.p_2[16] += (-0.029908461545777840 * params->param1[0]);
	params_1.p_2[17] = Inf;
	params_1.p_2[17] += (-0.837988659553745796 * params->param1[2]);
	params_1.p_2[17] += (-0.060567937082419122 * params->param1[1]);
	params_1.p_2[17] += (-0.001055472026708776 * params->param1[0]);
	params_1.p_2[18] = Inf;
	params_1.p_2[18] += (0.004477940797072812 * params->param1[2]);
	params_1.p_2[18] += (0.076666730431973917 * params->param1[1]);
	params_1.p_2[18] += (0.904787677462608908 * params->param1[0]);
	params_1.p_2[19] = 0.250000000000000000;
	params_1.p_2[19] += (0.095356131353786872 * params->param1[2]);
	params_1.p_2[19] += (0.804786282722455448 * params->param1[1]);
	params_1.p_2[19] += (0.038333365215986959 * params->param1[0]);
	params_1.p_2[20] = Inf;
	params_1.p_2[20] += (0.791187538504329657 * params->param1[2]);
	params_1.p_2[20] += (0.076284905083029486 * params->param1[1]);
	params_1.p_2[20] += (0.001791176318829124 * params->param1[0]);
	params_1.p_2[21] = 10.000000000000000000;
	params_1.p_2[21] += (-0.004477940797072812 * params->param1[2]);
	params_1.p_2[21] += (-0.076666730431973917 * params->param1[1]);
	params_1.p_2[21] += (-0.904787677462608908 * params->param1[0]);
	params_1.p_2[22] = 4.750000000000000000;
	params_1.p_2[22] += (-0.095356131353786872 * params->param1[2]);
	params_1.p_2[22] += (-0.804786282722455448 * params->param1[1]);
	params_1.p_2[22] += (-0.038333365215986959 * params->param1[0]);
	params_1.p_2[23] = Inf;
	params_1.p_2[23] += (-0.791187538504329657 * params->param1[2]);
	params_1.p_2[23] += (-0.076284905083029486 * params->param1[1]);
	params_1.p_2[23] += (-0.001791176318829124 * params->param1[0]);
	params_1.p_2[24] = Inf;
	params_1.p_2[24] += (0.006680470625627505 * params->param1[2]);
	params_1.p_2[24] += (0.092156317247951244 * params->param1[1]);
	params_1.p_2[24] += (0.882946478238693433 * params->param1[0]);
	params_1.p_2[25] = 0.250000000000000000;
	params_1.p_2[25] += (0.112631701371306098 * params->param1[2]);
	params_1.p_2[25] += (0.764125346667162586 * params->param1[1]);
	params_1.p_2[25] += (0.046078158623975622 * params->param1[0]);
	params_1.p_2[26] = Inf;
	params_1.p_2[26] += (0.747541207511138839 * params->param1[2]);
	params_1.p_2[26] += (0.090105361097044867 * params->param1[1]);
	params_1.p_2[26] += (0.002672188250251001 * params->param1[0]);
	params_1.p_2[27] = 10.000000000000000000;
	params_1.p_2[27] += (-0.006680470625627505 * params->param1[2]);
	params_1.p_2[27] += (-0.092156317247951244 * params->param1[1]);
	params_1.p_2[27] += (-0.882946478238693433 * params->param1[0]);
	params_1.p_2[28] = 4.750000000000000000;
	params_1.p_2[28] += (-0.112631701371306098 * params->param1[2]);
	params_1.p_2[28] += (-0.764125346667162586 * params->param1[1]);
	params_1.p_2[28] += (-0.046078158623975622 * params->param1[0]);
	params_1.p_2[29] = Inf;
	params_1.p_2[29] += (-0.747541207511138839 * params->param1[2]);
	params_1.p_2[29] += (-0.090105361097044867 * params->param1[1]);
	params_1.p_2[29] += (-0.002672188250251001 * params->param1[0]);
	params_1.p_2[30] = Inf;
	params_1.p_2[30] += (0.009186970003108540 * params->param1[2]);
	params_1.p_2[30] += (0.106383848692517116 * params->param1[1]);
	params_1.p_2[30] += (0.861820116839153605 * params->param1[0]);
	params_1.p_2[31] = 0.250000000000000000;
	params_1.p_2[31] += (0.127758444251923009 * params->param1[2]);
	params_1.p_2[31] += (0.726228291629362532 * params->param1[1]);
	params_1.p_2[31] += (0.053191924346258558 * params->param1[0]);
	params_1.p_2[32] = Inf;
	params_1.p_2[32] += (0.706813372346706270 * params->param1[2]);
	params_1.p_2[32] += (0.102206755401538396 * params->param1[1]);
	params_1.p_2[32] += (0.003674788001243416 * params->param1[0]);
	params_1.p_2[33] = 10.000000000000000000;
	params_1.p_2[33] += (-0.009186970003108540 * params->param1[2]);
	params_1.p_2[33] += (-0.106383848692517116 * params->param1[1]);
	params_1.p_2[33] += (-0.861820116839153605 * params->param1[0]);
	params_1.p_2[34] = 4.750000000000000000;
	params_1.p_2[34] += (-0.127758444251923009 * params->param1[2]);
	params_1.p_2[34] += (-0.726228291629362532 * params->param1[1]);
	params_1.p_2[34] += (-0.053191924346258558 * params->param1[0]);
	params_1.p_2[35] = Inf;
	params_1.p_2[35] += (-0.706813372346706270 * params->param1[2]);
	params_1.p_2[35] += (-0.102206755401538396 * params->param1[1]);
	params_1.p_2[35] += (-0.003674788001243416 * params->param1[0]);
	params_1.p_2[36] = Inf;
	params_1.p_2[36] += (0.011944340946679771 * params->param1[2]);
	params_1.p_2[36] += (0.119440101351922817 * params->param1[1]);
	params_1.p_2[36] += (0.841377089589093297 * params->param1[0]);
	params_1.p_2[37] = 0.250000000000000000;
	params_1.p_2[37] += (0.140938812350988041 * params->param1[2]);
	params_1.p_2[37] += (0.690882914751257071 * params->param1[1]);
	params_1.p_2[37] += (0.059720050675961416 * params->param1[0]);
	params_1.p_2[38] = Inf;
	params_1.p_2[38] += (0.668786435352378250 * params->param1[2]);
	params_1.p_2[38] += (0.112751049880790433 * params->param1[1]);
	params_1.p_2[38] += (0.004777736378671908 * params->param1[0]);
	params_1.p_2[39] = 10.000000000000000000;
	params_1.p_2[39] += (-0.011944340946679771 * params->param1[2]);
	params_1.p_2[39] += (-0.119440101351922817 * params->param1[1]);
	params_1.p_2[39] += (-0.841377089589093297 * params->param1[0]);
	params_1.p_2[40] = 4.750000000000000000;
	params_1.p_2[40] += (-0.140938812350988041 * params->param1[2]);
	params_1.p_2[40] += (-0.690882914751257071 * params->param1[1]);
	params_1.p_2[40] += (-0.059720050675961416 * params->param1[0]);
	params_1.p_2[41] = Inf;
	params_1.p_2[41] += (-0.668786435352378250 * params->param1[2]);
	params_1.p_2[41] += (-0.112751049880790433 * params->param1[1]);
	params_1.p_2[41] += (-0.004777736378671908 * params->param1[0]);
	params_1.p_2[42] = Inf;
	params_1.p_2[42] += (0.014905119427939399 * params->param1[2]);
	params_1.p_2[42] += (0.131409045247702527 * params->param1[1]);
	params_1.p_2[42] += (0.821587655847259346 * params->param1[0]);
	params_1.p_2[43] = 0.250000000000000000;
	params_1.p_2[43] += (0.152357543874096224 * params->param1[2]);
	params_1.p_2[43] += (0.657894088065200999 * params->param1[1]);
	params_1.p_2[43] += (0.065704522623851278 * params->param1[0]);
	params_1.p_2[44] = Inf;
	params_1.p_2[44] += (0.633259975295461297 * params->param1[2]);
	params_1.p_2[44] += (0.121886035099276979 * params->param1[1]);
	params_1.p_2[44] += (0.005962047771175759 * params->param1[0]);
	params_1.p_2[45] = 10.000000000000000000;
	params_1.p_2[45] += (-0.014905119427939399 * params->param1[2]);
	params_1.p_2[45] += (-0.131409045247702527 * params->param1[1]);
	params_1.p_2[45] += (-0.821587655847259346 * params->param1[0]);
	params_1.p_2[46] = 4.750000000000000000;
	params_1.p_2[46] += (-0.152357543874096224 * params->param1[2]);
	params_1.p_2[46] += (-0.657894088065200999 * params->param1[1]);
	params_1.p_2[46] += (-0.065704522623851278 * params->param1[0]);
	params_1.p_2[47] = Inf;
	params_1.p_2[47] += (-0.633259975295461297 * params->param1[2]);
	params_1.p_2[47] += (-0.121886035099276979 * params->param1[1]);
	params_1.p_2[47] += (-0.005962047771175759 * params->param1[0]);
	params_1.p_2[48] = Inf;
	params_1.p_2[48] += (0.018026957059454403 * params->param1[2]);
	params_1.p_2[48] += (0.142368378687942526 * params->param1[1]);
	params_1.p_2[48] += (0.802423721036186754 * params->param1[0]);
	params_1.p_2[49] = 0.250000000000000000;
	params_1.p_2[49] += (0.162183170759426565 * params->param1[2]);
	params_1.p_2[49] += (0.627082357692749781 * params->param1[1]);
	params_1.p_2[49] += (0.071184189343971277 * params->param1[0]);
	params_1.p_2[50] = Inf;
	params_1.p_2[50] += (0.600049352450525597 * params->param1[2]);
	params_1.p_2[50] += (0.129746536607541235 * params->param1[1]);
	params_1.p_2[50] += (0.007210782823781760 * params->param1[0]);
	params_1.p_2[51] = 10.000000000000000000;
	params_1.p_2[51] += (-0.018026957059454403 * params->param1[2]);
	params_1.p_2[51] += (-0.142368378687942526 * params->param1[1]);
	params_1.p_2[51] += (-0.802423721036186754 * params->param1[0]);
	params_1.p_2[52] = 4.750000000000000000;
	params_1.p_2[52] += (-0.162183170759426565 * params->param1[2]);
	params_1.p_2[52] += (-0.627082357692749781 * params->param1[1]);
	params_1.p_2[52] += (-0.071184189343971277 * params->param1[0]);
	params_1.p_2[53] = Inf;
	params_1.p_2[53] += (-0.600049352450525597 * params->param1[2]);
	params_1.p_2[53] += (-0.129746536607541235 * params->param1[1]);
	params_1.p_2[53] += (-0.007210782823781760 * params->param1[0]);
	params_1.p_2[54] = Inf;
	params_1.p_2[54] += (0.021272147893849715 * params->param1[2]);
	params_1.p_2[54] += (0.152390019844206387 * params->param1[1]);
	params_1.p_2[54] += (0.783858728313576059 * params->param1[0]);
	params_1.p_2[55] = 0.250000000000000000;
	params_1.p_2[55] += (0.170569399688372203 * params->param1[2]);
	params_1.p_2[55] += (0.598282658946600154 * params->param1[1]);
	params_1.p_2[55] += (0.076195009922103207 * params->param1[0]);
	params_1.p_2[56] = Inf;
	params_1.p_2[56] += (0.568984428525359576 * params->param1[2]);
	params_1.p_2[56] += (0.136455519750697779 * params->param1[1]);
	params_1.p_2[56] += (0.008508859157539884 * params->param1[0]);
	params_1.p_2[57] = 10.000000000000000000;
	params_1.p_2[57] += (-0.021272147893849715 * params->param1[2]);
	params_1.p_2[57] += (-0.152390019844206387 * params->param1[1]);
	params_1.p_2[57] += (-0.783858728313576059 * params->param1[0]);
	params_1.p_2[58] = 4.750000000000000000;
	params_1.p_2[58] += (-0.170569399688372203 * params->param1[2]);
	params_1.p_2[58] += (-0.598282658946600154 * params->param1[1]);
	params_1.p_2[58] += (-0.076195009922103207 * params->param1[0]);
	params_1.p_2[59] = Inf;
	params_1.p_2[59] += (-0.568984428525359576 * params->param1[2]);
	params_1.p_2[59] += (-0.136455519750697779 * params->param1[1]);
	params_1.p_2[59] += (-0.008508859157539884 * params->param1[0]);
	params_1.p_2[60] = Inf;
	params_1.p_2[60] += (0.024607196501277000 * params->param1[2]);
	params_1.p_2[60] += (0.161540558609569840 * params->param1[1]);
	params_1.p_2[60] += (0.765867558206770549 * params->param1[0]);
	params_1.p_2[61] = 0.250000000000000000;
	params_1.p_2[61] += (0.177656376844134961 * params->param1[2]);
	params_1.p_2[61] += (0.571343137708386961 * params->param1[1]);
	params_1.p_2[61] += (0.080770279304784934 * params->param1[0]);
	params_1.p_2[62] = Inf;
	params_1.p_2[62] += (0.539908391914890928 * params->param1[2]);
	params_1.p_2[62] += (0.142125101475307963 * params->param1[1]);
	params_1.p_2[62] += (0.009842878600510800 * params->param1[0]);
	params_1.p_2[63] = 10.000000000000000000;
	params_1.p_2[63] += (-0.024607196501277000 * params->param1[2]);
	params_1.p_2[63] += (-0.161540558609569840 * params->param1[1]);
	params_1.p_2[63] += (-0.765867558206770549 * params->param1[0]);
	params_1.p_2[64] = 4.750000000000000000;
	params_1.p_2[64] += (-0.177656376844134961 * params->param1[2]);
	params_1.p_2[64] += (-0.571343137708386961 * params->param1[1]);
	params_1.p_2[64] += (-0.080770279304784934 * params->param1[0]);
	params_1.p_2[65] = Inf;
	params_1.p_2[65] += (-0.539908391914890928 * params->param1[2]);
	params_1.p_2[65] += (-0.142125101475307963 * params->param1[1]);
	params_1.p_2[65] += (-0.009842878600510800 * params->param1[0]);
	params_1.p_2[66] = Inf;
	params_1.p_2[66] += (0.028002423813509942 * params->param1[2]);
	params_1.p_2[66] += (0.169881671998896200 * params->param1[1]);
	params_1.p_2[66] += (0.748426435587103867 * params->param1[0]);
	params_1.p_2[67] = 0.250000000000000000;
	params_1.p_2[67] += (0.183571846151146245 * params->param1[2]);
	params_1.p_2[67] += (0.546124069256356037 * params->param1[1]);
	params_1.p_2[67] += (0.084940835999448114 * params->param1[0]);
	params_1.p_2[68] = Inf;
	params_1.p_2[68] += (0.512676679557396264 * params->param1[2]);
	params_1.p_2[68] += (0.146857476920916968 * params->param1[1]);
	params_1.p_2[68] += (0.011200969525403977 * params->param1[0]);
	params_1.p_2[69] = 10.000000000000000000;
	params_1.p_2[69] += (-0.028002423813509942 * params->param1[2]);
	params_1.p_2[69] += (-0.169881671998896200 * params->param1[1]);
	params_1.p_2[69] += (-0.748426435587103867 * params->param1[0]);
	params_1.p_2[70] = 4.750000000000000000;
	params_1.p_2[70] += (-0.183571846151146245 * params->param1[2]);
	params_1.p_2[70] += (-0.546124069256356037 * params->param1[1]);
	params_1.p_2[70] += (-0.084940835999448114 * params->param1[0]);
	params_1.p_2[71] = Inf;
	params_1.p_2[71] += (-0.512676679557396264 * params->param1[2]);
	params_1.p_2[71] += (-0.146857476920916968 * params->param1[1]);
	params_1.p_2[71] += (-0.011200969525403977 * params->param1[0]);
	params_1.p_2[72] = Inf;
	params_1.p_2[72] += (0.031431607518353014 * params->param1[2]);
	params_1.p_2[72] += (0.177470506082611196 * params->param1[1]);
	params_1.p_2[72] += (0.731512843411273983 * params->param1[0]);
	params_1.p_2[73] = 0.250000000000000000;
	params_1.p_2[73] += (0.188432209915340182 * params->param1[2]);
	params_1.p_2[73] += (0.522496866451281572 * params->param1[1]);
	params_1.p_2[73] += (0.088735253041305612 * params->param1[0]);
	params_1.p_2[74] = Inf;
	params_1.p_2[74] += (0.487155987392481393 * params->param1[2]);
	params_1.p_2[74] += (0.150745767932272123 * params->param1[1]);
	params_1.p_2[74] += (0.012572643007341205 * params->param1[0]);
	params_1.p_2[75] = 10.000000000000000000;
	params_1.p_2[75] += (-0.031431607518353014 * params->param1[2]);
	params_1.p_2[75] += (-0.177470506082611196 * params->param1[1]);
	params_1.p_2[75] += (-0.731512843411273983 * params->param1[0]);
	params_1.p_2[76] = 4.750000000000000000;
	params_1.p_2[76] += (-0.188432209915340182 * params->param1[2]);
	params_1.p_2[76] += (-0.522496866451281572 * params->param1[1]);
	params_1.p_2[76] += (-0.088735253041305612 * params->param1[0]);
	params_1.p_2[77] = Inf;
	params_1.p_2[77] += (-0.487155987392481393 * params->param1[2]);
	params_1.p_2[77] += (-0.150745767932272123 * params->param1[1]);
	params_1.p_2[77] += (-0.012572643007341205 * params->param1[0]);
	params_1.p_2[78] = Inf;
	params_1.p_2[78] += (0.034871654058762323 * params->param1[2]);
	params_1.p_2[78] += (0.184360027197781384 * params->param1[1]);
	params_1.p_2[78] += (0.715105442703152128 * params->param1[0]);
	params_1.p_2[79] = 0.250000000000000000;
	params_1.p_2[79] += (0.192343500040272786 * params->param1[2]);
	params_1.p_2[79] += (0.500343169862197068 * params->param1[1]);
	params_1.p_2[79] += (0.092180013598890706 * params->param1[0]);
	params_1.p_2[80] = Inf;
	params_1.p_2[80] += (0.463223362085126766 * params->param1[2]);
	params_1.p_2[80] += (0.153874800032218206 * params->param1[1]);
	params_1.p_2[80] += (0.013948661623504929 * params->param1[0]);
	params_1.p_2[81] = 10.000000000000000000;
	params_1.p_2[81] += (-0.034871654058762323 * params->param1[2]);
	params_1.p_2[81] += (-0.184360027197781384 * params->param1[1]);
	params_1.p_2[81] += (-0.715105442703152128 * params->param1[0]);
	params_1.p_2[82] = 4.750000000000000000;
	params_1.p_2[82] += (-0.192343500040272786 * params->param1[2]);
	params_1.p_2[82] += (-0.500343169862197068 * params->param1[1]);
	params_1.p_2[82] += (-0.092180013598890706 * params->param1[0]);
	params_1.p_2[83] = Inf;
	params_1.p_2[83] += (-0.463223362085126766 * params->param1[2]);
	params_1.p_2[83] += (-0.153874800032218206 * params->param1[1]);
	params_1.p_2[83] += (-0.013948661623504929 * params->param1[0]);
	params_1.p_2[84] = Inf;
	params_1.p_2[84] += (0.038302299539124590 * params->param1[2]);
	params_1.p_2[84] += (0.190599344953396616 * params->param1[1]);
	params_1.p_2[84] += (0.699183998291884379 * params->param1[0]);
	params_1.p_2[85] = 0.250000000000000000;
	params_1.p_2[85] += (0.195402267311204275 * params->param1[2]);
	params_1.p_2[85] += (0.479554013030641657 * params->param1[1]);
	params_1.p_2[85] += (0.095299672476698308 * params->param1[0]);
	params_1.p_2[86] = Inf;
	params_1.p_2[86] += (0.440765367289569054 * params->param1[2]);
	params_1.p_2[86] += (0.156321813848963403 * params->param1[1]);
	params_1.p_2[86] += (0.015320919815649835 * params->param1[0]);
	params_1.p_2[87] = 10.000000000000000000;
	params_1.p_2[87] += (-0.038302299539124590 * params->param1[2]);
	params_1.p_2[87] += (-0.190599344953396616 * params->param1[1]);
	params_1.p_2[87] += (-0.699183998291884379 * params->param1[0]);
	params_1.p_2[88] = 4.750000000000000000;
	params_1.p_2[88] += (-0.195402267311204275 * params->param1[2]);
	params_1.p_2[88] += (-0.479554013030641657 * params->param1[1]);
	params_1.p_2[88] += (-0.095299672476698308 * params->param1[0]);
	params_1.p_2[89] = Inf;
	params_1.p_2[89] += (-0.440765367289569054 * params->param1[2]);
	params_1.p_2[89] += (-0.156321813848963403 * params->param1[1]);
	params_1.p_2[89] += (-0.015320919815649835 * params->param1[0]);
	params_1.p_2[90] = Inf;
	params_1.p_2[90] += (0.041705837068416921 * params->param1[2]);
	params_1.p_2[90] += (0.196234009338695087 * params->param1[1]);
	params_1.p_2[90] += (0.683729309861115242 * params->param1[0]);
	params_1.p_2[91] = 0.250000000000000000;
	params_1.p_2[91] += (0.197696395613353976 * params->param1[2]);
	params_1.p_2[91] += (0.460029056637876466 * params->param1[1]);
	params_1.p_2[91] += (0.098117004669347543 * params->param1[0]);
	params_1.p_2[92] = Inf;
	params_1.p_2[92] += (0.419677318285550549 * params->param1[2]);
	params_1.p_2[92] += (0.158157116490683175 * params->param1[1]);
	params_1.p_2[92] += (0.016682334827366765 * params->param1[0]);
	params_1.p_2[93] = 10.000000000000000000;
	params_1.p_2[93] += (-0.041705837068416921 * params->param1[2]);
	params_1.p_2[93] += (-0.196234009338695087 * params->param1[1]);
	params_1.p_2[93] += (-0.683729309861115242 * params->param1[0]);
	params_1.p_2[94] = 4.750000000000000000;
	params_1.p_2[94] += (-0.197696395613353976 * params->param1[2]);
	params_1.p_2[94] += (-0.460029056637876466 * params->param1[1]);
	params_1.p_2[94] += (-0.098117004669347543 * params->param1[0]);
	params_1.p_2[95] = Inf;
	params_1.p_2[95] += (-0.419677318285550549 * params->param1[2]);
	params_1.p_2[95] += (-0.158157116490683175 * params->param1[1]);
	params_1.p_2[95] += (-0.016682334827366765 * params->param1[0]);
	params_1.p_2[96] = Inf;
	params_1.p_2[96] += (0.045066868278210485 * params->param1[2]);
	params_1.p_2[96] += (0.201306284052581080 * params->param1[1]);
	params_1.p_2[96] += (0.668723147899935921 * params->param1[0]);
	params_1.p_2[97] = 0.250000000000000000;
	params_1.p_2[97] += (0.199305847376851808 * params->param1[2]);
	params_1.p_2[97] += (0.441675885858166140 * params->param1[1]);
	params_1.p_2[97] += (0.100653142026290526 * params->param1[0]);
	params_1.p_2[98] = Inf;
	params_1.p_2[98] += (0.399862579331730361 * params->param1[2]);
	params_1.p_2[98] += (0.159444677901481424 * params->param1[1]);
	params_1.p_2[98] += (0.018026747311284192 * params->param1[0]);
	params_1.p_2[99] = 10.000000000000000000;
	params_1.p_2[99] += (-0.045066868278210485 * params->param1[2]);
	params_1.p_2[99] += (-0.201306284052581080 * params->param1[1]);
	params_1.p_2[99] += (-0.668723147899935921 * params->param1[0]);
	params_1.p_2[100] = 4.750000000000000000;
	params_1.p_2[100] += (-0.199305847376851808 * params->param1[2]);
	params_1.p_2[100] += (-0.441675885858166140 * params->param1[1]);
	params_1.p_2[100] += (-0.100653142026290526 * params->param1[0]);
	params_1.p_2[101] = Inf;
	params_1.p_2[101] += (-0.399862579331730361 * params->param1[2]);
	params_1.p_2[101] += (-0.159444677901481424 * params->param1[1]);
	params_1.p_2[101] += (-0.018026747311284192 * params->param1[0]);
	params_1.p_2[102] = Inf;
	params_1.p_2[102] += (0.048372076944275304 * params->param1[2]);
	params_1.p_2[102] += (0.205855397997234124 * params->param1[1]);
	params_1.p_2[102] += (0.654148194179005826 * params->param1[0]);
	params_1.p_2[103] = 0.250000000000000000;
	params_1.p_2[103] += (0.200303346015089812 * params->param1[2]);
	params_1.p_2[103] += (0.424409365656679416 * params->param1[1]);
	params_1.p_2[103] += (0.102927698998617034 * params->param1[0]);
	params_1.p_2[104] = Inf;
	params_1.p_2[104] += (0.381231918550689552 * params->param1[2]);
	params_1.p_2[104] += (0.160242676812071827 * params->param1[1]);
	params_1.p_2[104] += (0.019348830777710116 * params->param1[0]);
	params_1.p_2[105] = 10.000000000000000000;
	params_1.p_2[105] += (-0.048372076944275304 * params->param1[2]);
	params_1.p_2[105] += (-0.205855397997234124 * params->param1[1]);
	params_1.p_2[105] += (-0.654148194179005826 * params->param1[0]);
	params_1.p_2[106] = 4.750000000000000000;
	params_1.p_2[106] += (-0.200303346015089812 * params->param1[2]);
	params_1.p_2[106] += (-0.424409365656679416 * params->param1[1]);
	params_1.p_2[106] += (-0.102927698998617034 * params->param1[0]);
	params_1.p_2[107] = Inf;
	params_1.p_2[107] += (-0.381231918550689552 * params->param1[2]);
	params_1.p_2[107] += (-0.160242676812071827 * params->param1[1]);
	params_1.p_2[107] += (-0.019348830777710116 * params->param1[0]);
	params_1.p_2[108] = Inf;
	params_1.p_2[108] += (0.051610022815349044 * params->param1[2]);
	params_1.p_2[108] += (0.209917776718576560 * params->param1[1]);
	params_1.p_2[108] += (0.639987986405452181 * params->param1[0]);
	params_1.p_2[109] = 0.250000000000000000;
	params_1.p_2[109] += (0.200755000641233305 * params->param1[2]);
	params_1.p_2[109] += (0.408151049226436469 * params->param1[1]);
	params_1.p_2[109] += (0.104958888359288252 * params->param1[0]);
	params_1.p_2[110] = Inf;
	params_1.p_2[110] += (0.363702915590526032 * params->param1[2]);
	params_1.p_2[110] += (0.160604000512986622 * params->param1[1]);
	params_1.p_2[110] += (0.020644009126139611 * params->param1[0]);
	params_1.p_2[111] = 10.000000000000000000;
	params_1.p_2[111] += (-0.051610022815349044 * params->param1[2]);
	params_1.p_2[111] += (-0.209917776718576560 * params->param1[1]);
	params_1.p_2[111] += (-0.639987986405452181 * params->param1[0]);
	params_1.p_2[112] = 4.750000000000000000;
	params_1.p_2[112] += (-0.200755000641233305 * params->param1[2]);
	params_1.p_2[112] += (-0.408151049226436469 * params->param1[1]);
	params_1.p_2[112] += (-0.104958888359288252 * params->param1[0]);
	params_1.p_2[113] = Inf;
	params_1.p_2[113] += (-0.363702915590526032 * params->param1[2]);
	params_1.p_2[113] += (-0.160604000512986622 * params->param1[1]);
	params_1.p_2[113] += (-0.020644009126139611 * params->param1[0]);
	params_1.p_2[114] = Inf;
	params_1.p_2[114] += (0.054770953912785782 * params->param1[2]);
	params_1.p_2[114] += (0.213527255429146218 * params->param1[1]);
	params_1.p_2[114] += (0.626226866737842225 * params->param1[0]);
	params_1.p_2[115] = 0.250000000000000000;
	params_1.p_2[115] += (0.200720877905923134 * params->param1[2]);
	params_1.p_2[115] += (0.392828635158313899 * params->param1[1]);
	params_1.p_2[115] += (0.106763627714573067 * params->param1[0]);
	params_1.p_2[116] = Inf;
	params_1.p_2[116] += (0.347199417702778457 * params->param1[2]);
	params_1.p_2[116] += (0.160576702324738502 * params->param1[1]);
	params_1.p_2[116] += (0.021908381565114307 * params->param1[0]);
	params_1.p_2[117] = 10.000000000000000000;
	params_1.p_2[117] += (-0.054770953912785782 * params->param1[2]);
	params_1.p_2[117] += (-0.213527255429146218 * params->param1[1]);
	params_1.p_2[117] += (-0.626226866737842225 * params->param1[0]);
	params_1.p_2[118] = 4.750000000000000000;
	params_1.p_2[118] += (-0.200720877905923134 * params->param1[2]);
	params_1.p_2[118] += (-0.392828635158313899 * params->param1[1]);
	params_1.p_2[118] += (-0.106763627714573067 * params->param1[0]);
	params_1.p_2[119] = Inf;
	params_1.p_2[119] += (-0.347199417702778457 * params->param1[2]);
	params_1.p_2[119] += (-0.160576702324738502 * params->param1[1]);
	params_1.p_2[119] += (-0.021908381565114307 * params->param1[0]);
	params_1.p_2[120] = Inf;
	params_1.p_2[120] += (0.057846635711524937 * params->param1[2]);
	params_1.p_2[120] += (0.216715275114005540 * params->param1[1]);
	params_1.p_2[120] += (0.612849933867952168 * params->param1[0]);
	params_1.p_2[121] = 0.250000000000000000;
	params_1.p_2[121] += (0.200255525394335554 * params->param1[2]);
	params_1.p_2[121] += (0.378375469304437773 * params->param1[1]);
	params_1.p_2[121] += (0.108357637557002728 * params->param1[0]);
	params_1.p_2[122] = Inf;
	params_1.p_2[122] += (0.331651040238323591 * params->param1[2]);
	params_1.p_2[122] += (0.160204420315468415 * params->param1[1]);
	params_1.p_2[122] += (0.023138654284609969 * params->param1[0]);
	params_1.p_2[123] = 10.000000000000000000;
	params_1.p_2[123] += (-0.057846635711524937 * params->param1[2]);
	params_1.p_2[123] += (-0.216715275114005540 * params->param1[1]);
	params_1.p_2[123] += (-0.612849933867952168 * params->param1[0]);
	params_1.p_2[124] = 4.750000000000000000;
	params_1.p_2[124] += (-0.200255525394335554 * params->param1[2]);
	params_1.p_2[124] += (-0.378375469304437773 * params->param1[1]);
	params_1.p_2[124] += (-0.108357637557002728 * params->param1[0]);
	params_1.p_2[125] = Inf;
	params_1.p_2[125] += (-0.331651040238323591 * params->param1[2]);
	params_1.p_2[125] += (-0.160204420315468415 * params->param1[1]);
	params_1.p_2[125] += (-0.023138654284609969 * params->param1[0]);
	params_1.p_2[126] = Inf;
	params_1.p_2[126] += (0.060830195747239205 * params->param1[2]);
	params_1.p_2[126] += (0.219511063096593045 * params->param1[1]);
	params_1.p_2[126] += (0.599842998399407912 * params->param1[0]);
	params_1.p_2[127] = 0.250000000000000000;
	params_1.p_2[127] += (0.199408450649690372 * params->param1[2]);
	params_1.p_2[127] += (0.364730087631119082 * params->param1[1]);
	params_1.p_2[127] += (0.109755531548296481 * params->param1[0]);
	params_1.p_2[128] = Inf;
	params_1.p_2[128] += (0.316992707894692638 * params->param1[2]);
	params_1.p_2[128] += (0.159526760519752259 * params->param1[1]);
	params_1.p_2[128] += (0.024332078298895679 * params->param1[0]);
	params_1.p_2[129] = 10.000000000000000000;
	params_1.p_2[129] += (-0.060830195747239205 * params->param1[2]);
	params_1.p_2[129] += (-0.219511063096593045 * params->param1[1]);
	params_1.p_2[129] += (-0.599842998399407912 * params->param1[0]);
	params_1.p_2[130] = 4.750000000000000000;
	params_1.p_2[130] += (-0.199408450649690372 * params->param1[2]);
	params_1.p_2[130] += (-0.364730087631119082 * params->param1[1]);
	params_1.p_2[130] += (-0.109755531548296481 * params->param1[0]);
	params_1.p_2[131] = Inf;
	params_1.p_2[131] += (-0.316992707894692638 * params->param1[2]);
	params_1.p_2[131] += (-0.159526760519752259 * params->param1[1]);
	params_1.p_2[131] += (-0.024332078298895679 * params->param1[0]);
	params_1.p_2[132] = Inf;
	params_1.p_2[132] += (0.063715982317661235 * params->param1[2]);
	params_1.p_2[132] += (0.221941799327956074 * params->param1[1]);
	params_1.p_2[132] += (0.587192541274723201 * params->param1[0]);
	params_1.p_2[133] = 0.250000000000000000;
	params_1.p_2[133] += (0.198224559550193996 * params->param1[2]);
	params_1.p_2[133] += (0.351835796665354972 * params->param1[1]);
	params_1.p_2[133] += (0.110970899663978009 * params->param1[0]);
	params_1.p_2[134] = Inf;
	params_1.p_2[134] += (0.303164233352457346 * params->param1[2]);
	params_1.p_2[134] += (0.158579647640155169 * params->param1[1]);
	params_1.p_2[134] += (0.025486392927064488 * params->param1[0]);
	params_1.p_2[135] = 10.000000000000000000;
	params_1.p_2[135] += (-0.063715982317661235 * params->param1[2]);
	params_1.p_2[135] += (-0.221941799327956074 * params->param1[1]);
	params_1.p_2[135] += (-0.587192541274723201 * params->param1[0]);
	params_1.p_2[136] = 4.750000000000000000;
	params_1.p_2[136] += (-0.198224559550193996 * params->param1[2]);
	params_1.p_2[136] += (-0.351835796665354972 * params->param1[1]);
	params_1.p_2[136] += (-0.110970899663978009 * params->param1[0]);
	params_1.p_2[137] = Inf;
	params_1.p_2[137] += (-0.303164233352457346 * params->param1[2]);
	params_1.p_2[137] += (-0.158579647640155169 * params->param1[1]);
	params_1.p_2[137] += (-0.025486392927064488 * params->param1[0]);
	params_1.p_2[138] = Inf;
	params_1.p_2[138] += (0.066499436058894787 * params->param1[2]);
	params_1.p_2[138] += (0.224032769558744432 * params->param1[1]);
	params_1.p_2[138] += (0.574885675021960196 * params->param1[0]);
	params_1.p_2[139] = 0.250000000000000000;
	params_1.p_2[139] += (0.196744557454687025 * params->param1[2]);
	params_1.p_2[139] += (0.339640288421163616 * params->param1[1]);
	params_1.p_2[139] += (0.112016384779372202 * params->param1[0]);
	params_1.p_2[140] = Inf;
	params_1.p_2[140] += (0.290109930217241796 * params->param1[2]);
	params_1.p_2[140] += (0.157395645963749581 * params->param1[1]);
	params_1.p_2[140] += (0.026599774423557907 * params->param1[0]);
	params_1.p_2[141] = 10.000000000000000000;
	params_1.p_2[141] += (-0.066499436058894787 * params->param1[2]);
	params_1.p_2[141] += (-0.224032769558744432 * params->param1[1]);
	params_1.p_2[141] += (-0.574885675021960196 * params->param1[0]);
	params_1.p_2[142] = 4.750000000000000000;
	params_1.p_2[142] += (-0.196744557454687025 * params->param1[2]);
	params_1.p_2[142] += (-0.339640288421163616 * params->param1[1]);
	params_1.p_2[142] += (-0.112016384779372202 * params->param1[0]);
	params_1.p_2[143] = Inf;
	params_1.p_2[143] += (-0.290109930217241796 * params->param1[2]);
	params_1.p_2[143] += (-0.157395645963749581 * params->param1[1]);
	params_1.p_2[143] += (-0.026599774423557907 * params->param1[0]);
	params_1.p_2[144] = Inf;
	params_1.p_2[144] += (0.069176973280851914 * params->param1[2]);
	params_1.p_2[144] += (0.225807506457908341 * params->param1[1]);
	params_1.p_2[144] += (0.562910107610336663 * params->param1[0]);
	params_1.p_2[145] = 0.250000000000000000;
	params_1.p_2[145] += (0.195005316246571303 * params->param1[2]);
	params_1.p_2[145] += (0.328095286950770393 * params->param1[1]);
	params_1.p_2[145] += (0.112903753228954171 * params->param1[0]);
	params_1.p_2[146] = Inf;
	params_1.p_2[146] += (0.277778257439629139 * params->param1[2]);
	params_1.p_2[146] += (0.156004252997257009 * params->param1[1]);
	params_1.p_2[146] += (0.027670789312340759 * params->param1[0]);
	params_1.p_2[147] = 10.000000000000000000;
	params_1.p_2[147] += (-0.069176973280851914 * params->param1[2]);
	params_1.p_2[147] += (-0.225807506457908341 * params->param1[1]);
	params_1.p_2[147] += (-0.562910107610336663 * params->param1[0]);
	params_1.p_2[148] = 4.750000000000000000;
	params_1.p_2[148] += (-0.195005316246571303 * params->param1[2]);
	params_1.p_2[148] += (-0.328095286950770393 * params->param1[1]);
	params_1.p_2[148] += (-0.112903753228954171 * params->param1[0]);
	params_1.p_2[149] = Inf;
	params_1.p_2[149] += (-0.277778257439629139 * params->param1[2]);
	params_1.p_2[149] += (-0.156004252997257009 * params->param1[1]);
	params_1.p_2[149] += (-0.027670789312340759 * params->param1[0]);
	params_1.p_2[150] = Inf;
	params_1.p_2[150] += (0.071745880040614052 * params->param1[2]);
	params_1.p_2[150] += (0.227287919654516085 * params->param1[1]);
	params_1.p_2[150] += (0.551254108720731217 * params->param1[0]);
	params_1.p_2[151] = 0.250000000000000000;
	params_1.p_2[151] += (0.193040210143746338 * params->param1[2]);
	params_1.p_2[151] += (0.317156223902880618 * params->param1[1]);
	params_1.p_2[151] += (0.113643959827258043 * params->param1[0]);
	params_1.p_2[152] = Inf;
	params_1.p_2[152] += (0.266121492619681654 * params->param1[2]);
	params_1.p_2[152] += (0.154432168114997048 * params->param1[1]);
	params_1.p_2[152] += (0.028698352016245612 * params->param1[0]);
	params_1.p_2[153] = 10.000000000000000000;
	params_1.p_2[153] += (-0.071745880040614052 * params->param1[2]);
	params_1.p_2[153] += (-0.227287919654516085 * params->param1[1]);
	params_1.p_2[153] += (-0.551254108720731217 * params->param1[0]);
	params_1.p_2[154] = 4.750000000000000000;
	params_1.p_2[154] += (-0.193040210143746338 * params->param1[2]);
	params_1.p_2[154] += (-0.317156223902880618 * params->param1[1]);
	params_1.p_2[154] += (-0.113643959827258043 * params->param1[0]);
	params_1.p_2[155] = Inf;
	params_1.p_2[155] += (-0.266121492619681654 * params->param1[2]);
	params_1.p_2[155] += (-0.154432168114997048 * params->param1[1]);
	params_1.p_2[155] += (-0.028698352016245612 * params->param1[0]);
	params_1.p_2[156] = Inf;
	params_1.p_2[156] += (0.074204216019219116 * params->param1[2]);
	params_1.p_2[156] += (0.228494415598828632 * params->param1[1]);
	params_1.p_2[156] += (0.539906478252314082 * params->param1[0]);
	params_1.p_2[157] = 0.250000000000000000;
	params_1.p_2[157] += (0.190879422902301948 * params->param1[2]);
	params_1.p_2[157] += (0.306781940687748389 * params->param1[1]);
	params_1.p_2[157] += (0.114247207799414316 * params->param1[0]);
	params_1.p_2[158] = Inf;
	params_1.p_2[158] += (0.255095431817753127 * params->param1[2]);
	params_1.p_2[158] += (0.152703538321841525 * params->param1[1]);
	params_1.p_2[158] += (0.029681686407687639 * params->param1[0]);
	params_1.p_2[159] = 10.000000000000000000;
	params_1.p_2[159] += (-0.074204216019219116 * params->param1[2]);
	params_1.p_2[159] += (-0.228494415598828632 * params->param1[1]);
	params_1.p_2[159] += (-0.539906478252314082 * params->param1[0]);
	params_1.p_2[160] = 4.750000000000000000;
	params_1.p_2[160] += (-0.190879422902301948 * params->param1[2]);
	params_1.p_2[160] += (-0.306781940687748389 * params->param1[1]);
	params_1.p_2[160] += (-0.114247207799414316 * params->param1[0]);
	params_1.p_2[161] = Inf;
	params_1.p_2[161] += (-0.255095431817753127 * params->param1[2]);
	params_1.p_2[161] += (-0.152703538321841525 * params->param1[1]);
	params_1.p_2[161] += (-0.029681686407687639 * params->param1[0]);
	params_1.p_2[162] = Inf;
	params_1.p_2[162] += (0.076550727346792899 * params->param1[2]);
	params_1.p_2[162] += (0.229446008065138179 * params->param1[1]);
	params_1.p_2[162] += (0.528856516900572005 * params->param1[0]);
	params_1.p_2[163] = 0.250000000000000000;
	params_1.p_2[163] += (0.188550228821768195 * params->param1[2]);
	params_1.p_2[163] += (0.296934415048128675 * params->param1[1]);
	params_1.p_2[163] += (0.114723004032569090 * params->param1[0]);
	params_1.p_2[164] = Inf;
	params_1.p_2[164] += (0.244659113690360003 * params->param1[2]);
	params_1.p_2[164] += (0.150840183057414506 * params->param1[1]);
	params_1.p_2[164] += (0.030620290938717154 * params->param1[0]);
	params_1.p_2[165] = 10.000000000000000000;
	params_1.p_2[165] += (-0.076550727346792899 * params->param1[2]);
	params_1.p_2[165] += (-0.229446008065138179 * params->param1[1]);
	params_1.p_2[165] += (-0.528856516900572005 * params->param1[0]);
	params_1.p_2[166] = 4.750000000000000000;
	params_1.p_2[166] += (-0.188550228821768195 * params->param1[2]);
	params_1.p_2[166] += (-0.296934415048128675 * params->param1[1]);
	params_1.p_2[166] += (-0.114723004032569090 * params->param1[0]);
	params_1.p_2[167] = Inf;
	params_1.p_2[167] += (-0.244659113690360003 * params->param1[2]);
	params_1.p_2[167] += (-0.150840183057414506 * params->param1[1]);
	params_1.p_2[167] += (-0.030620290938717154 * params->param1[0]);

	/* call solver #1 */
	exitflag = internal_simpleMPC_solver_1_solve(&params_1, &output_1, &info_1, fs );

	/* iterations */
	info->it = info_1.it;

	/* iterations to optimality (branch and bound) */
	info->it2opt = info_1.it2opt;

	/* res_eq */
	info->res_eq = info_1.res_eq;

	/* res_ineq */
	info->res_ineq = info_1.res_ineq;

	/* pobj */
	info->pobj = info_1.pobj;

	/* dobj */
	info->dobj = info_1.dobj;

	/* dgap */
	info->dgap = info_1.dgap;

	/* rdgap */
	info->rdgap = info_1.rdgap;

	/* mu */
	info->mu = info_1.mu;

	/* mu_aff */
	info->mu_aff = info_1.mu_aff;

	/* sigma */
	info->sigma = info_1.sigma;

	/* lsit_aff */

	info->lsit_aff = info_1.lsit_aff;

	/* lsit_cc */
	info->lsit_cc = info_1.lsit_cc;

	/* step_aff */
	info->step_aff = info_1.step_aff;

	/* step_cc */
	info->step_cc = info_1.step_cc;

	/* solver time */
	info->solvetime = info_1.solvetime;


	/* OUTPUTS -----------------------------------------------------------*/
	/*Build outputs*/
	output->output1[0] = (1.000000000000000000 * output_1.o_1[0]);

	output->output1[1] = (1.000000000000000000 * output_1.o_2[0]);

	output->output1[2] = (1.000000000000000000 * output_1.o_3[0]);

	output->output1[3] = (1.000000000000000000 * output_1.o_4[0]);

	output->output1[4] = (1.000000000000000000 * output_1.o_5[0]);

	output->output1[5] = (1.000000000000000000 * output_1.o_6[0]);

	output->output1[6] = (1.000000000000000000 * output_1.o_7[0]);

	output->output1[7] = (1.000000000000000000 * output_1.o_8[0]);

	output->output1[8] = (1.000000000000000000 * output_1.o_9[0]);

	output->output1[9] = (1.000000000000000000 * output_1.o_10[0]);

	output->output1[10] = (1.000000000000000000 * output_1.o_11[0]);

	output->output1[11] = (1.000000000000000000 * output_1.o_12[0]);

	output->output1[12] = (1.000000000000000000 * output_1.o_13[0]);

	output->output1[13] = (1.000000000000000000 * output_1.o_14[0]);

	output->output1[14] = (1.000000000000000000 * output_1.o_15[0]);

	output->output1[15] = (1.000000000000000000 * output_1.o_16[0]);

	output->output1[16] = (1.000000000000000000 * output_1.o_17[0]);

	output->output1[17] = (1.000000000000000000 * output_1.o_18[0]);

	output->output1[18] = (1.000000000000000000 * output_1.o_19[0]);

	output->output1[19] = (1.000000000000000000 * output_1.o_20[0]);

	output->output1[20] = (1.000000000000000000 * output_1.o_21[0]);

	output->output1[21] = (1.000000000000000000 * output_1.o_22[0]);

	output->output1[22] = (1.000000000000000000 * output_1.o_23[0]);

	output->output1[23] = (1.000000000000000000 * output_1.o_24[0]);

	output->output1[24] = (1.000000000000000000 * output_1.o_25[0]);

	output->output1[25] = (1.000000000000000000 * output_1.o_26[0]);

	output->output1[26] = (1.000000000000000000 * output_1.o_27[0]);

	output->output1[27] = (1.000000000000000000 * output_1.o_28[0]);

	output->output1[28] = (1.000000000000000000 * output_1.o_29[0]);

	output->output1[29] = (1.000000000000000000 * output_1.o_30[0]);

	output->output1[30] = (1.000000000000000000 * output_1.o_31[0]);

	output->output1[31] = (1.000000000000000000 * output_1.o_32[0]);

	output->output1[32] = (1.000000000000000000 * output_1.o_33[0]);

	output->output1[33] = (1.000000000000000000 * output_1.o_34[0]);

	output->output1[34] = (1.000000000000000000 * output_1.o_35[0]);

	output->output1[35] = (1.000000000000000000 * output_1.o_36[0]);

	output->output1[36] = (1.000000000000000000 * output_1.o_37[0]);

	output->output1[37] = (1.000000000000000000 * output_1.o_38[0]);

	output->output1[38] = (1.000000000000000000 * output_1.o_39[0]);

	output->output1[39] = (1.000000000000000000 * output_1.o_40[0]);

	output->output1[40] = (1.000000000000000000 * output_1.o_41[0]);

	output->output1[41] = (1.000000000000000000 * output_1.o_42[0]);

	output->output1[42] = (1.000000000000000000 * output_1.o_43[0]);

	output->output1[43] = (1.000000000000000000 * output_1.o_44[0]);

	output->output1[44] = (1.000000000000000000 * output_1.o_45[0]);

	output->output1[45] = (1.000000000000000000 * output_1.o_46[0]);

	output->output1[46] = (1.000000000000000000 * output_1.o_47[0]);

	output->output1[47] = (1.000000000000000000 * output_1.o_48[0]);

	output->output1[48] = (1.000000000000000000 * output_1.o_49[0]);

	output->output1[49] = (1.000000000000000000 * output_1.o_50[0]);

	output->output1[50] = (1.000000000000000000 * output_1.o_51[0]);

	output->output1[51] = (1.000000000000000000 * output_1.o_52[0]);

	output->output1[52] = (1.000000000000000000 * output_1.o_53[0]);

	output->output1[53] = (1.000000000000000000 * output_1.o_54[0]);

	output->output1[54] = (1.000000000000000000 * output_1.o_55[0]);

	output->output1[55] = (1.000000000000000000 * output_1.o_56[0]);

	output->output1[56] = (1.000000000000000000 * output_1.o_57[0]);

	output->output1[57] = (1.000000000000000000 * output_1.o_58[0]);

	return exitflag;
}